<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class adminController extends CRUDController
{
//    public function __construct()
//    {
//        $this->middleware('auth');
//    }

    public function index()
    {
        return view('admin');
//        parent::index(); // TODO: Change the autogenerated stub
    }


}
