<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class userController extends CRUDController
{
//    public function __construct()
//    {
//        $this->middleware('auth');
//    }

    public function index()
    {
        return view('index');
//        parent::index(); // TODO: Change the autogenerated stub
    }


}
